/**
 * Created by harsh on 7/5/16.
 */

const DATA_SHEETNAME = "#import";
const METADATA_SHEET = "settings";
const TRACKER_PROGRAM_UID = "ProgramUID";
const TRACKER_TRACKED_ENTITY = "TrackedEntityUID";
const TRACKER_REGISTRATION_PLUS_ENROLLMENT = "TRACKER_REGISTRATION_PLUS_ENROLLMENT";


const FIRST_DELIMITER = "#";
const SECOND_DELIMITER = "@";
const THIRD_DELIMITER = ".";

const DOMAIN_TEI = "tei";
const DOMAIN_EVENT = "ev";
const DOMAIN_ENROLLMENT = "en";
const DOMAIN_DATA_ELEMENT = "de";

const DOMAINS = [DOMAIN_TEI,
                 DOMAIN_ENROLLMENT,
                  DOMAIN_EVENT,DOMAIN_DATA_ELEMENT  ];

const FIELD_DATAELEMENT = "de";
const FIELD_ATTRIBUTE = "attr";
const FIELD_REGISTRATION_DATE = "registrationDate";
const FIELD_ORG_UNIT = "ou";
const FIELD_TRACKED_ENTITY = "te";
const FIELD_TRACKED_ENTITY_INSTANCE = "tei";
const FIELD_PROGRAM = "prg";
const FIELD_PROGRAM_STAGE = "ps";
const FIELD_EVENT_DATE="eventDate";
const FIELD_NAME = "name";
const FIELD_STORED_BY = "storedBy";
const FIELD_ENROLLMENT_DATE = "enrollmentDate";


const FIELDS = [FIELD_DATAELEMENT,
                FIELD_ATTRIBUTE,FIELD_REGISTRATION_DATE,FIELD_ORG_UNIT,FIELD_TRACKED_ENTITY,FIELD_NAME,
    FIELD_PROGRAM,FIELD_ENROLLMENT_DATE,FIELD_EVENT_DATE,FIELD_STORED_BY,FIELD_TRACKED_ENTITY_INSTANCE,
    FIELD_PROGRAM_STAGE
                ]



